/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutIcon: typeof import('@nutui/nutui-taro')['Icon']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
